Alguns métodos tornados estáticos.
matheusfelipeog/calculadora-tk pull request #11
Opened 2020-09-03 13:23 UTC by mateusnssp

Creio que seja uma alternativa mais fluida e segura pois os métodos não usam o `self` e muito menos alteram a instância das classes.

2020-09-03 16:33 UTC, matheusfelipeog commented
@mateusnssp, obrigado pela contribuição. 😄 

Muito bem observado, realmente a utilização do `staticmethod` é melhor para os casos que modificou.

Vou revisar e, caso todo o código da calculadora esteja de acordo com o contexto do seu PR, aprovo para o merge. Caso contrário, abro um code review.

2020-09-03 17:36 UTC, matheusfelipeog requested changes
Essas são as duas revisões. Caso discorde de alguma, me informe o motivo para podermos falar sobre 😀

2020-09-03 17:36 UTC, matheusfelipeog commented on app/calculador.py
>              return self.__format_result(result=result)
Como o tipo do método foi alterado para estático, é interessante alterar os locais onde ele é chamado. 

Isto não é um erro, e sim uma alteração para dar contexto. Deixando o chamado sendo feito pela instância (`self.__format_result(...)`) pode-se confundir com um método comum.

```suggestion
            return Calculador.__format_result(result=result)
```

Note que, feito essa alteração que sugeri, os métodos `__calculation_validation` e `calculation` também não vão utilizar mais a variável que faz referência à instância (`self`). 

Já que a alteração inicial resulta na mesma ideia que comentei no inicio, todos os métodos terão que ter seu tipo e chamado alterado. Ficando algo semelhante a:  `Calculador.__calculation_validation` e `Calculador.calculation`, com o primeiro sendo feito no arquivo `app/calculador.py` e o segundo em `app/calculadora.py` quando é instânciado.

Assim, todos os métodos da classe se tornariam estáticos. Esse tipo de resultado mostra que a utilização de uma classe para essa finalidade não é necessária, podendo ser resolvido com simples funções.

Caso queira resolver esse problema que descrevi por completo, será o máximo 😆. Senão, pode somente fazer a alteração da sugestão que fiz no inicio e futuramente faço uma refatoração em todo código.

2020-09-03 17:36 UTC, matheusfelipeog commented on app/calculadora.py
> +    def _lenght_max(data_in_input):
Aqui também entra na mesma ideia do review anterior, todos os chamados que usam a variável que aponta para a instância (`self._lenght_max(...)`) devem ser alterados para `Calculadora._lenght_max(...)`.

2020-09-04 13:43 UTC, mateusnssp commented
Pensando bem realmente é melhor manter contexto no código por completo! Vou estudar mais a fundo e ver se consigo reestruturar nessa questão por completo :laughing: é um caso interessante

2020-09-04 16:30 UTC, matheusfelipeog commented
Excelente, fico no aguardo para receber suas modificações 😄

Caso tenha alguma dúvida/dificuldade, sinta-se a vontade para perguntar aqui.

2020-10-08 14:05 UTC, matheusfelipeog commented
@mateusnssp, como esse PR está aberto e é elegível para o evento hacktoberfest, deixo este aviso.

O evento [hacktoberfest](https://hacktoberfest.digitalocean.com/) começou, caso queira ganhar a camisa e pontuar para completar os requisitos do evento basta completar este PR que, após merge, será contabilizado :)

Você pode saber mais visitando o link destacado.

2021-03-23 14:15 UTC, matheusfelipeog commented
PR fechado por inatividade.

2021-03-23 14:15 UTC, closed without merging